language: go
go:
  - 1.x

env:
 - PATH=$PATH:$GOPATH/bin

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/mattn/goveralls

install:
  - ./bin/install_tools.sh
  - dep ensure

script:
  - ./bin/check_fmt.sh
  - ./bin/check_mocks.sh
  - ./bin/coveralls.sh
