language: go
go:
  - stable

env:
 - PATH=$PATH:$GOPATH/bin

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - ./bin/check_fmt.sh
  - ./bin/check_mocks.sh
  - ./bin/coveralls.sh
