language: go
go:
  - stable

env:
 - PATH=$PATH:$GOPATH/bin GO111MODULE=on

before_install:
  - ./bin/install_tools.sh

install:
  - go mod download

script:
  - ./bin/check_fmt.sh
  - ./bin/check_mocks.sh
  - ./bin/coveralls.sh
